name: CD - React.js

on:
  push:
    branches: [main]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm i

    - name: Build the app
      run: npm run build

    - name: Deploy to production
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        ssh $USERNAME@$HOST "rm -rf /home/jaja/nimdaauto.jaja.id/*"
        scp -r build/* $USERNAME@$HOST:/home/jaja/nimdaauto.jaja.id/
        ssh $USERNAME@$HOST "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && pm2 restart nimdaauto"
